### ISSUE TITLE
Incompatibility with openapi-spec-validator-0.5.0

### ISSUE THREAD

**Issue by jayvdb** [TheWall89/inducoapi#3]
When running with openapi-spec-validator v0.5.0, the following occurs, so it looks like there have been some breaking changes.

```py
> python3.10 -m inducoapi
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/inducoapi/__main__.py", line 20, in <module>
    from openapi_spec_validator.exceptions import OpenAPIValidationError
ImportError: cannot import name 'OpenAPIValidationError' from 'openapi_spec_validator.exceptions' (/usr/lib/python3.10/site-packages/openapi_spec_validator/exceptions.py)
```

**Comment by TheWall89** [comment]
Hello and thanks for the report. I'll try to look into this as soon as possible.
